### ISSUE TITLE
BUG: Responsive table layout

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-metadata#4]
Wide table don't behave very well right now --- I think we just need to wrap the table in a `.table-responsive` and then the layout should be a bit cleaner.

**Comment by ebolyen** [comment]
There isn't a good way to do this with DataTables. We tried the Responsive plugin, but that makes every row expandable and is kind of strange. Otherwise, there isn't a good way to affix the bootstrap class as the JQuery plugin is managing the DOM and we don't really want to change that underneath.

All of the data is still very accessible, the buttons and search bar just aren't fixed to the viewport, but that isn't the end of the world.
